---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
        service: auth
    spec:
      containers:
        - name: auth
          image: basilnsage/mwn-ticketapp.auth:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: 256Mi
          env:
            - name: JWT_SIGN_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: sign-key
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 4000
      targetPort: 4000
...
