---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scape_interval: 15s
      external_labels:
        monitor: prom-monitor
    scrape_configs:
      - job_name: prometheus
        scape_interval: 5s
        static_configs:
          - targets:
            - localhost:9090
...
