---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      external_labels:
        monitor: prom-monitor
    scrape_configs:
      - job_name: prometheus
        scrape_interval: 5s
        static_configs:
          - targets:
            - localhost:9090
      - job_name: ticket-auth
        kubernetes_sd_configs:
          - role: service
            selectors:
              - role: service
                label: "service=auth"
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
            replacement: pod_label_$1
          - action: replace
            source_labels:
              - __meta_kubernetes_namespace
            target_label: kubernetes_namespace
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_name
            target_label: kubernetes_name
...
