{
 "title": "Kubernetes / API server",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(apiserver_request_total, cluster)"
   },
   {
    "name": "instance",
    "query": "label_values(apiserver_request_total{job=\"apiserver\", cluster=\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Notice",
   "type": "text",
   "description": "Display various SLOs by which we monitor tickets.dev",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": { "content": "tickets.dev SLOs" }
  },
  {
   "title": "Auth Request Rate",
   "type": "graph",
   "description": "Auth service request rate",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(request_duration_seconds_count{route!=\"/metrics\"}[5m])"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "graph",
   "description": "What is the latency per route/method/response code?",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, rate(request_duration_seconds_bucket[5m]))"
    }
   ]
  },
  {
   "title": "Mean 4XX Growth",
   "type": "stat",
   "description": "What is the mean growth in 4XX responses?",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(request_duration_seconds_count{code=~\"4\\\\d+\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Percent 4XX (no metrics)",
   "type": "graph",
   "description": "What percentage of requests (excluding prometheus scrapping) resulted in a 4XX response?",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(request_duration_seconds_count{code=~\"4\\\\d+\", route!=\"/metrics\"}[$__range])) / sum(increase(request_duration_seconds_count{route!=\"/metrics\"}[$__range]))",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "Mean 5XX Growth",
   "type": "stat",
   "description": "What is the mean growth in 5XX responses?",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(request_duration_seconds_count{code=~\"500+\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Percent 5XX (no metrics)",
   "type": "graph",
   "description": "What percentage of requests (excluding prometheus scrapping) results in a 5XX response?",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(request_duration_seconds_count{code=~\"500+\", route!=\"/metrics\"}[$__range])) / sum(increase(request_duration_seconds_count{route!=\"/metrics\"}[$__range]))",
     "legendFormat": "{{ resource }}"
    }
   ]
  }
 ]
}