---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-storage-pv
spec:
  storageClassName: "local-storage"
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /run/desktop/mnt/host/d/docker-desktop-volumes/prometheus/storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - docker-desktop
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-storage-pvc
spec:
  storageClassName: local-storage
  volumeName: prom-storage-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
    limits:
      storage: 10Gi
...
