---
name: build and deploy the client service
on:
  push:
    branches:
    - master
    paths:
    - 'client/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: sign in to Docker
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}    
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}    
    - name: build image
      run: docker build -t basilnsage/mwn-ticketapp.client:latest client/
    - name: publish image
      run: docker push basilnsage/mwn-ticketapp.client:latest
    - name: set kubectl context
      run: doctl kubernetes cluster kubeconfig save 2f69198b-6f3f-44a6-94cc-fc19cdf1a023
    - name: update client service
      run: kubectl rollout restart deployment client-depl
...